### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by Goddchen** [Goddchen/flutter_native_logs#13]
A readme that will also be nicely displayed on pub.dev

**Comment by milansurelia** [comment]
@Goddchen  Can you share a brief description of `What the package does?`, it will be helpful writing README.md

**Comment by Goddchen** [comment]
Hey, thanks for your interest in the project 😎 
Sure. I have already startet to write something in the [`feature/readme`](/Goddchen/flutter_native_logs/tree/feature/readme/README.md)  branch. Is this already enough info for you to continue? Feel to free to create a PR out of this branch when it's finished.
