### ISSUE TITLE
Do not log by default

### ISSUE THREAD

**Issue by VitaliBov** [Goddchen/flutter_native_logs#25]
Hi @Goddchen,
I use flutter_native_logs for logging in dev environment so that testers can quickly provide full application logs.
I don't use logging in prod environment so as not to load the cpu:
```
    if (isLogEnabled) {
      FlutterNativeLogs().logStream.listen((message) => _logs.add('${message.message}\n'));
    }
```

But I found that the plugin still sends logs to the channel in the onAttachedToEngine method.
Which is the best way to turn off the sending of logs? Maybe a` start()` method should be added to start the thread?

**Comment by Goddchen** [comment]
Good point. I'm still thinking about if it makes sense to add `start()/stop()` methods or if it is enough to just start the background process once someone calls `listen(...)` on the `logStream` and kill it after the stream subscription is cancelled.

@VitaliBov  Do you have any preference?

**Comment by VitaliBov** [comment]
@Goddchen I like both options as they do the same thing but in different ways. And each way will solve the problem
